# SPDX-License-Identifier: MIT-0
---
- name: Prepare deployment workspace
  import_tasks: 01_setup.yaml
  tags: setup

- name: Copy compose file
  import_tasks: 02_configs.yaml
  tags: configs

- name: Deploy containers
  import_tasks: 03_deploy.yaml
  tags: deploy

- name: Debug build number
  debug:
    msg: "Build number is {{ build_number }}"

- name: Clean up old images
  import_tasks: 04_cleanup.yaml
  tags: cleanup